create table if not exists app_users (
  id bigserial primary key,
  email text not null unique,
  name text not null,
  password_hash text not null,
  role text not null default 'buyer' check (role in ('buyer', 'seller', 'admin')),
  privacy_consent_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists app_sessions (
  token_hash char(64) primary key,
  user_id bigint not null references app_users(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists app_sessions_expiry_idx on app_sessions (expires_at);

create table if not exists profiles (
  user_id bigint primary key references app_users(id) on delete cascade,
  gender text not null default '',
  birthday date,
  phone text not null default '',
  address text not null default '',
  address_data jsonb not null default '{}'::jsonb,
  avatar_data text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  owner_id bigint references app_users(id) on delete set null,
  name text not null,
  description text not null default '',
  price numeric(12, 2) not null check (price > 0),
  emoji text not null default '📦',
  photo_data text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists products_created_at_idx on products (created_at desc);

create table if not exists orders (
  id text primary key,
  buyer_id bigint not null references app_users(id) on delete restrict,
  buyer_email text not null,
  buyer_name text not null,
  items jsonb not null check (jsonb_typeof(items) = 'array'),
  total numeric(12, 2) not null check (total >= 0),
  delivery_address text not null,
  payment_method text not null,
  status text not null default 'To Ship'
    check (status in ('To Ship', 'To Receive', 'Completed', 'Cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists orders_buyer_created_idx on orders (buyer_id, created_at desc);

create table if not exists messages (
  id bigserial primary key,
  buyer_id bigint not null references app_users(id) on delete cascade,
  sender_id bigint not null references app_users(id) on delete restrict,
  sender_role text not null check (sender_role in ('buyer', 'seller', 'admin')),
  body text not null check (length(body) between 1 and 5000),
  created_at timestamptz not null default now()
);
create index if not exists messages_buyer_created_idx on messages (buyer_id, created_at);

create table if not exists notifications (
  id bigserial primary key,
  user_id bigint not null references app_users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);
create index if not exists notifications_user_created_idx on notifications (user_id, created_at desc);
